<?php

return array(
    'Ă' => 'A', // A with breve
    'ă' => 'a', // a with breve
    'A̧' => 'A', // A with cedilla
    'a̧' => 'a', // a with cedilla
    'A̭' => 'A', // A with circumflex below
    'a̭' => 'a', // a with circumflex below
    'A̐' => 'A', // A with chandrabindu
    'a̐' => 'a', // a with chandrabindu
    'A̓' => 'A', // A with comma above
    'a̓' => 'a', // a with comma above
    'A̋' => 'A', // A with double acute
    'a̋' => 'a', // a with double acute
    'Å' => 'A', // A with ring above
    'å' => 'a', // a with ring above
    'Å̂' => 'A', // A with ring above and circumflex
    'å̂' => 'a', // a with ring above and circumflex
    'A̰' => 'A', // A with tilde below
    'a̰' => 'a', // a with tilde below
    'Ą' => 'A', // A with ogonek
    'ą' => 'a', // a with ogonek
    'Ą́' => 'A', // A with acute and ogonek
    'ą́' => 'a', // a with acute and ogonek
    'Ą̀' => 'A', // A with grave and ogonek
    'ą̀' => 'a', // a with grave and ogonek
    'Ą̂' => 'A', // A with circumflex and ogonek
    'ą̂' => 'a', // a with circumflex and ogonek
    'Ą̌' => 'A', // A with acute and ogonek
    'ą̌' => 'a', // a with acute and ogonek
    'Ą̄' => 'A', // A with macron and ogonek
    'ą̄' => 'a', // a with macron and ogonek
    'Ą̄́' => 'A', // A with macron, acute and ogonek
    'ą̄́' => 'a', // a with macron, acute and ogonek
    'Ą̄̀' => 'A', // A with macron, grave and ogonek
    'ą̄̀' => 'a', // a with macron, grave and ogonek
    'Ą̄̂' => 'A', // A with macron, circumflex and ogonek
    'ą̄̂' => 'a', // a with macron, circumflex and ogonek
    'Ą̄̌' => 'A', // A with macron, caron and ogonek
    'ą̄̌' => 'a', // a with macron, caron and ogonek
    'Ā̊' => 'A', // A with macron and ring above
    'ā̊' => 'a', // a with macron and ring above
    'Ą̊' => 'A', // A with ring above and ogonek
    'ą̊' => 'a', // a with ring above and ogonek
    'Ą̃' => 'A', // A with tilde and ogonek
    'ą̃' => 'a', // a with tilde and ogonek
    'Ą̈' => 'A', // A with diaeresis and ogonek
    'ą̈' => 'a', // a with diaeresis and ogonek
    'Ą̈̀' => 'A', // A with diaeresis, grave and ogonek
    'ą̈̀' => 'a', // a with diaeresis, grave and ogonek
    'Ą̈̂' => 'A', // A with diaeresis, circumflex and ogonek
    'ą̈̂' => 'a', // a with diaeresis, circumflex and ogonek
    'Ą̈̌' => 'A', // A with diaeresis, caron and ogonek
    'ą̈̌' => 'a', // a with diaeresis, caron and ogonek
    'A᷎' => 'A', // A with ogonek above
    'a᷎' => 'a', // a with ogonek above
    'Ā' => 'A', // A with macron
    'ā' => 'a', // a with macron
    'Ā́' => 'A', // A with macron and acute
    'ā́' => 'a', // a with macron and acute
    'Ā̀' => 'A', // A with macron and grave
    'ā̀' => 'a', // a with macron and grave
    'Ā̂' => 'A', // A with macron and circumflex
    'ā̂' => 'a', // a with macron and circumflex
    'Ā̌' => 'A', // A with macron and caron
    'ā̌' => 'a', // a with macron and caron
    'Ā̆' => 'A', // A with macron and breve
    'ā̆' => 'a', // a with macron and breve
    'A̱' => 'A', // A with macron below
    'a̱' => 'a', // a with macron below
    'Ā̱' => 'A', // A with macron below and macron
    'ā̱' => 'a', // a with macron below and macron
    'Å̱' => 'A', // A with macron below and ring above
    'å̱' => 'a', // a with macron below and ring above
    'A̍' => 'A', // A with vertical line
    'a̍' => 'a', // a with vertical line
    'B́' => 'B', // B with acute
    'b́' => 'b', // b with acute
    'B̓' => 'B', // B with comma above
    'b̓' => 'b', // b with comma above
    'Ḃ' => 'B', // B with dot above
    'ḃ' => 'b', // b with dot above
    'B̃' => 'B', // B with tilde
    'b̃' => 'b', // b with tilde
    'B̤' => 'B', // B with diaeresis below
    'b̤' => 'b', // b with diaeresis below
    'C̀' => 'C', // C with grave
    'c̀' => 'c', // c with grave
    'C̆' => 'C', // C with breve
    'c̆' => 'c', // c with breve
    'Č' => 'C', // C with caron
    'č' => 'c', // c with caron
    'Č̓' => 'C', // C with caron and comma above
    'č̓' => 'c', // c with caron and comma above
    'C̓' => 'C', // C with comma above
    'c̓' => 'c', // c with comma above
    'C̈' => 'C', // C with diaeresis
    'c̈' => 'c', // c with diaeresis
    'Ċ' => 'C', // C with dot above
    'ċ' => 'c', // c with dot above
    'C̣' => 'C', // C with dot below
    'c̣' => 'c', // c with dot below
    'Ç' => 'C', // C with cedilla
    'ç' => 'c', // c with cedilla
    'Ç̆' => 'C', // C with cedilla and breve
    'ç̆' => 'c', // c with cedilla and breve
    'Ç̌' => 'C', // C with cedilla and caron
    'ç̌' => 'c', // c with cedilla and caron
    'Ç̇' => 'C', // C with cedilla and dot above
    'ç̇' => 'c', // c with cedilla and dot above
    'C̄' => 'C', // C with macron
    'c̄' => 'c', // c with macron
    'C̃' => 'C', // C with tilde
    'c̃' => 'c', // c with tilde
    'D́' => 'D', // D with acute
    'd́' => 'd', // d with acute
    'Ď' => 'D', // D with caron
    'ď' => 'd', // d with caron
    'D̂' => 'D', // D with circumflex
    'd̂' => 'd', // d with circumflex
    'D̓' => 'D', // D with comma above
    'd̓' => 'd', // d with comma above
    'D̦' => 'D', // D with comma below
    'd̦' => 'd', // d with comma below
    'Ḋ' => 'D', // D with dot above
    'ḋ' => 'd', // d with dot above
    'D̤' => 'D', // D with diaeresis below
    'd̤' => 'd', // d with diaeresis below
    'Đ' => 'D', // D with stroke
    'đ' => 'd', // d with stroke
    'Ĕ' => 'E', // E with breve
    'ĕ' => 'e', // e with breve
    'Ě' => 'E', // E with caron
    'ě' => 'e', // e with caron
    'E̋' => 'E', // E with double acute
    'e̋' => 'e', // e with double acute
    'Ė' => 'E', // E with dot above
    'ė' => 'e', // e with dot above
    'Ė́' => 'E', // E with dot above and acute
    'ė́' => 'e', // e with dot above and acute
    'Ė̃' => 'E', // E with dot and macron
    'ė̃' => 'e', // e with dot and macron
    'Ę' => 'E', // E with ogonek
    'ę' => 'e', // e with ogonek
    'Ę́' => 'E', // E with acute and ogonek
    'ę́' => 'e', // e with acute and ogonek
    'Ę̀' => 'E', // E with grave and ogonek
    'ę̀' => 'e', // e with grave and ogonek
    'Ę̂' => 'E', // E with circumflex and ogonek
    'ę̂' => 'e', // e with circumflex and ogonek
    'Ę̌' => 'E', // E with caron and ogonek
    'ę̌' => 'e', // e with caron and ogonek
    'Ę̄' => 'E', // E with macron and ogonek
    'ę̄' => 'e', // e with macron and ogonek
    'Ę̄́' => 'E', // E with macron, acute and ogonek
    'ę̄́' => 'e', // e with macron, acute and ogonek
    'Ę̄̀' => 'E', // E with macron, grave and ogonek
    'ę̄̀' => 'e', // e with macron, grave and ogonek
    'Ę̄̂' => 'E', // E with macron, circumflex and ogonek
    'ę̄̂' => 'e', // e with macron, circumflex and ogonek
    'Ę̄̌' => 'E', // E with macron, caron and ogonek
    'ę̄̌' => 'e', // e with macron, caron and ogonek
    'Ę̃' => 'E', // E with tilde and ogonek
    'ę̃' => 'e', // e with tilde and ogonek
    'Ę̈' => 'E', // E with diaeresis and ogonek
    'ę̈' => 'e', // e with diaeresis and ogonek
    'Ę̈̀' => 'E', // E with diaeresis, grave and ogonek
    'ę̈̀' => 'e', // e with diaeresis, grave and ogonek
    'Ę̈̂' => 'E', // E with diaeresis, circumflex and ogonek
    'ę̈̂' => 'e', // e with diaeresis, circumflex and ogonek
    'Ę̈̌' => 'E', // E with diaeresis, caron and ogonek
    'ę̈̌' => 'e', // e with diaeresis, caron and ogonek
    'Ę̇́' => 'E', // E with dot above, acute and ogonek
    'ę̇́' => 'e', // e with dot above, acute and ogonek
    'Ę̋' => 'E', // E with double acute and ogonek
    'ę̋' => 'e', // e with double acute and ogonek
    'Ę̇' => 'E', // E with dot above and ogonek
    'ę̇' => 'e', // e with dot above and ogonek
    'Ę̣' => 'E', // E with ogonek and dot below
    'ę̣' => 'e', // e with ogonek and dot below
    'Ę᷎' => 'E', // E with ogonek above and ogonek
    'ę᷎' => 'e', // e with ogonek above and ogonek
    'E᷎' => 'E', // E with ogonek above
    'e᷎' => 'e', // e with ogonek above
    'Ē' => 'E', // E with macron
    'ē' => 'e', // e with macron
    'Ē̆' => 'E', // E with macron and breve
    'ē̆' => 'e', // e with macron and breve
    'Ē̂' => 'E', // E with macron and circumflex
    'ē̂' => 'e', // e with macron and circumflex
    'Ē̌' => 'E', // E with macron and caron
    'ē̌' => 'e', // e with macron and caron
    'E̍' => 'E', // E with vertical line
    'e̍' => 'e', // e with vertical line
    'E̱' => 'E', // E with macron below
    'e̱' => 'e', // e with macron below
    'Ē̱' => 'E', // E with macron and macron below
    'ē̱' => 'e', // e with macron and macron below
    'E̊' => 'E', // E with ring
    'e̊' => 'e', // e with ring
    'F́' => 'F', // F with acute
    'f́' => 'f', // f with acute
    'F̀' => 'F', // F with grave
    'f̀' => 'f', // f with grave
    'Ḟ' => 'F', // F with dot above
    'ḟ' => 'f', // f with dot above
    'F̄' => 'F', // F with macron
    'f̄' => 'f', // f with macron
    'F̧' => 'F', // F with cedilla
    'f̧' => 'f', // f with cedilla
    'ƒ' => 'f', // f with hook (Script F)
    'F̣' => 'F', // F with dot below
    'f̣' => 'f', // f with dot below
    'G̀' => 'G', // G with grave
    'g̀' => 'g', // g with grave
    'Ğ' => 'G', // G with breve
    'ğ' => 'g', // g with breve
    'Ġ' => 'G', // G with dot above
    'ġ' => 'g', // g with dot above
    'G̣' => 'G', // G with dot below
    'g̣' => 'g', // g with dot below
    'Ģ' => 'G', // G with cedilla
    'ģ' => 'g', // g with cedilla
    'G̈' => 'G', // G with diaeresis
    'g̈' => 'g', // g with diaeresis
    'G̤' => 'G', // G with diaeresis below
    'g̤' => 'g', // g with diaeresis below
    'G̃' => 'G', // G with tilde
    'g̃' => 'g', // g with tilde
    'H́' => 'H', // H with acute
    'h́' => 'h', // h with acute
    'H̤' => 'H', // H with diaeresis below
    'h̤' => 'h', // h with diaeresis below
    'H̄' => 'H', // H with macron
    'h̄' => 'h', // h with macron
    'H̐' => 'H', // H with chandrabindu
    'h̐' => 'h', // h with chandrabindu
    'H̓' => 'H', // H with comma above
    'h̓' => 'h', // h with comma above
    'H̱' => 'H', // H with line below
    'Ħ' => 'H', // H with stroke
    'ħ' => 'h', // h with stroke
    'Ĭ' => 'I', // I with breve
    'ĭ' => 'i', // i with breve
    'İ' => 'I', // I (uppercase) with dot above
    'i' => 'i', // i (uppercase) with dot above
    'I' => 'I', // I (lowercase, i.e. ı) without dot above
    'ı' => 'i', // i (lowercase, i.e. ı) without dot above
    'Į' => 'I', // I with ogonek
    'į' => 'i', // i with ogonek
    'Į́' => 'I', // I with ogonek and acute
    'į́' => 'i', // i with ogonek and acute
    'Į̀' => 'I', // I with ogonek and grave
    'į̀' => 'i', // i with ogonek and grave
    'Į̂' => 'I', // I with ogonek and circumflex
    'į̂' => 'i', // i with ogonek and circumflex
    'Į̌' => 'I', // I with ogonek and caron
    'į̌' => 'i', // i with ogonek and caron
    'Į̃' => 'I', // I with ogonek and tilde
    'į̃' => 'i', // i with ogonek and tilde
    'Ī' => 'I', // I with macron
    'ī' => 'i', // i with macron
    'Ī́' => 'I', // I with macron and acute
    'ī́' => 'i', // i with macron and acute
    'Ī̀' => 'I', // I with macron and grave
    'ī̀' => 'i', // i with macron and grave
    'Ī̂' => 'I', // I with macron and circumflex
    'ī̂' => 'i', // i with macron and circumflex
    'Ī̌' => 'I', // I with macron and caron
    'ī̌' => 'i', // i with macron and caron
    'I̋' => 'I', // I with double acute
    'i̋' => 'i', // i with double acute
    'I̍' => 'I', // I with vertical line
    'i̍' => 'i', // i with vertical line
    'I̐' => 'I', // I with chandrabindu
    'i̐' => 'i', // i with chandrabindu
    'I̓' => 'I', // I with comma above
    'i̓' => 'i', // i with comma above
    'I̧' => 'I', // I with cedilla
    'i̧' => 'i', // i with cedilla
    'I̱' => 'I', // I with line below
    'i̱' => 'i', // i with line below
    'Ī̱' => 'I', // I with line below and macron
    'ī̱' => 'i', // i with line below and macron
    'J́' => 'J', // J with acute
    'j́' => 'j', // j with acute
    'J̌' => 'J', // J with caron
    'J̄' => 'J', // J with macron
    'j̄' => 'j', // j with macron
    'J̃' => 'J', // J with tilde
    'j̃' => 'j', // j with tilde
    'J̣' => 'J', // J with dot below
    'j̣' => 'j', // j with dot below
    'K̀' => 'K', // K with grave
    'k̀' => 'k', // k with grave
    'K̄' => 'K', // K with macron
    'k̄' => 'k', // k with macron
    'K̇' => 'K', // K with dot above
    'k̇' => 'k', // k with dot above
    'Ķ' => 'K', // K with cedilla
    'ķ' => 'k', // k with cedilla
    'Ĺ' => 'L', // L with acute
    'ĺ' => 'l', // l with acute
    'L̂' => 'L', // L with circumflex
    'l̂' => 'l', // l with circumflex
    'L̐' => 'L', // L with chandrabindu
    'l̐' => 'l', // l with chandrabindu
    'L̃' => 'L', // L with tilde
    'l̃' => 'l', // l with tilde
    'L̓' => 'L', // L with comma above
    'l̓' => 'l', // l with comma above
    'Ľ' => 'L', // L with caron
    'ľ' => 'l', // l with caron
    'Ļ' => 'L', // L with cedilla
    'ļ' => 'l', // l with cedilla
    'L̦' => 'L', // L with comma below
    'l̦' => 'l', // l with comma below
    'Ł' => 'L', // L with stroke
    'ł' => 'l', // l with stroke
    'M̀' => 'M', // M with grave
    'm̀' => 'm', // m with grave
    'Ṁ' => 'M', // M with dot above
    'ṁ' => 'm', // m with dot above
    'M̍' => 'M', // M with vertical line
    'm̍' => 'm', // m with vertical line
    'M̄' => 'M', // M with macron
    'm̄' => 'm', // m with macron
    'M̐' => 'M', // M with chandrabindu
    'm̐' => 'm', // m with chandrabindu
    'M̃' => 'M', // M with tilde
    'm̃' => 'm', // m with tilde
    'M̈' => 'M', // M with diaeresis
    'm̈' => 'm', // m with diaeresis
    'M̓' => 'M', // M with comma above
    'm̓' => 'm', // m with comma above
    'M̧' => 'M', // M with cedilla
    'm̧' => 'm', // m with cedilla
    'M̨' => 'M', // M with ogonek
    'm̨' => 'm', // m with ogonek
    'M̦' => 'M', // M with comma below
    'm̦' => 'm', // m with comma below
    'N̂' => 'N', // N with circumflex
    'n̂' => 'n', // n with circumflex
    'Ň' => 'N', // N with caron
    'ň' => 'n', // n with caron
    'N̍' => 'N', // N with vertical line
    'n̍' => 'n', // n with vertical line
    'N̄' => 'N', // N with macron
    'n̄' => 'n', // n with macron
    'N̐' => 'N', // N with chandrabindu
    'n̐' => 'n', // n with chandrabindu
    'N̈' => 'N', // N with diaresis
    'n̈' => 'n', // n with diaresis
    'Ņ' => 'N', // N with cedilla
    'ņ' => 'n', // n with cedilla
    'N̦' => 'N', // N with comma below
    'n̦' => 'n', // n with comma below
    'N̰' => 'N', // N with tilde below
    'n̰' => 'n', // n with tilde below
    'N̲' => 'N', // N with underline
    'n̲' => 'n', // n with underline
    'Ŏ' => 'O', // O with breve
    'ŏ' => 'o', // o with breve
    'O̐' => 'O', // O with chandrabindu
    'o̐' => 'o', // o with chandrabindu
    'O͘' => 'O', // O with dot above right
    'o͘' => 'o', // o with dot above right
    'Ō͘' => 'O', // O with dot above right and macron
    'ō͘' => 'o', // o with dot above right and macron
    'O̍͘' => 'O', // O with dot above and vertical line
    'o̍͘' => 'o', // o with dot above and vertical line
    'Ø' => 'O', // O with stroke
    'ø' => 'o', // o with stroke
    'Ø̀' => 'O', // O with stroke and grave
    'ø̀' => 'o', // o with stroke and grave
    'Ø̂' => 'O', // O with stroke and circumflex
    'ø̂' => 'o', // o with stroke and circumflex
    'Ø̌' => 'O', // O with stroke and caron
    'ø̌' => 'o', // o with stroke and caron
    'Ø̄' => 'O', // O with stroken and macron
    'ø̄' => 'o', // o with stroken and macron
    'Ō' => 'O', // O with macron
    'ō' => 'o', // o with macron
    'Ō̂' => 'O', // O with macron and circumflex
    'ō̂' => 'o', // o with macron and circumflex
    'Ō̌' => 'O', // O with macron and caron
    'ō̌' => 'o', // o with macron and caron
    'O̍' => 'O', // O with vertical line
    'o̍' => 'o', // o with vertical line
    'O̭' => 'O', // O with circumflex below
    'o̭' => 'o', // o with circumflex below
    'O̧' => 'O', // O with cedilla
    'o̧' => 'o', // o with cedilla
    'O̱' => 'O', // O with line below
    'o̱' => 'o', // o with line below
    'Ō̱' => 'O', // O with macron and line below
    'ō̱' => 'o', // o with macron and line below
    'O̲' => 'O', // O with underline
    'o̲' => 'o', // o with underline
    'P̀' => 'P', // P with grave
    'p̀' => 'p', // p with grave
    'Ṗ' => 'P', // P with dot above
    'ṗ' => 'p', // p with dot above
    'P̣' => 'P', // P with dot above below
    'p̣' => 'p', // p with dot above below
    'P̄' => 'P', // P with macron
    'p̄' => 'p', // p with macron
    'P̓' => 'P', // P with comma above
    'p̓' => 'p', // p with comma above
    'P̈' => 'P', // P with diaeresis
    'p̈' => 'p', // p with diaeresis
    'P̤' => 'P', // P with diaeresis below
    'p̤' => 'p', // p with diaeresis below
    'P̄' => 'P', // P with tilde
    'p̄' => 'p', // p with tilde
    'Q̓' => 'Q', // Q with comma above
    'q̓' => 'q', // q with comma above
    'Q̇' => 'Q', // Q with dot above
    'q̇' => 'q', // q with dot above
    'Ř' => 'R', // R with caron
    'ř' => 'r', // r with caron
    'R̂' => 'R', // R with circumflex
    'r̂' => 'r', // r with circumflex
    'R̓' => 'R', // R with comma above
    'r̓' => 'r', // r with comma above
    'R̦' => 'R', // R with comma below
    'r̦' => 'r', // r with comma below
    'Ŗ' => 'R', // R with cedilla
    'ŗ' => 'r', // r with cedilla
    'R̄' => 'R', // R with macron
    'r̄' => 'r', // r with macron
    'R̰' => 'R', // R with diaeresis below
    'r̰' => 'r', // r with diaeresis below
    'R̥' => 'R', // R with ring below
    'r̥' => 'r', // r with ring below
    'R̥̄' => 'R', // R with ring below and macron
    'r̥̄' => 'r', // r with ring below and macron
    'R̃' => 'R', // R with tilde
    'r̃' => 'r', // r with tilde
    'Š' => 'S', // S with caron
    'š' => 's', // s with caron
    'Ṡ' => 'S', // S with dot above
    'ṡ' => 's', // s with dot above
    'Ş' => 'S', // S with cedilla
    'ş' => 's', // s with cedilla
    'Ș' => 'S', // S with comma below
    'ș' => 's', // s with comma below
    'Ť' => 'T', // T with caron
    'ť' => 't', // t with caron
    'T̈' => 'T', // T with diaeresis
    'Ṫ' => 'T', // T with dot above
    'ṫ' => 't', // t with dot above
    'Ţ' => 'T', // T with cedilla
    'ţ' => 't', // t with cedilla
    'Ț' => 'T', // T with comma below
    'ț' => 't', // t with comma below
    'Ŧ' => 'T', // T with stroke
    'ŧ' => 't', // t with stroke
    'Ŭ' => 'U', // U with breve
    'ŭ' => 'u', // u with breve
    'Ů' => 'U', // U with ring above
    'ů' => 'u', // u with ring above
    'Ų' => 'U', // U with ogonek
    'ų' => 'u', // u with ogonek
    'Ū' => 'U', // U with macron
    'ū' => 'u', // u with macron
    'W̊' => 'W', // W with ring above
    'Y̊' => 'Y', // Y with ring above
    'Ž' => 'Z', // Z with caron
    'ž' => 'z', // z with caron
    'Ż' => 'Z', // Z with dot above
    'ż' => 'z', // z with dot above
);
