<?php

return array(
    'Á' => 'A', // A with acute
    'á' => 'a', // a with acute
    'À' => 'A', // A with grave
    'à' => 'a', // a with grave
    'Ă' => 'A', // A with breve
    'ă' => 'a', // a with breve
    'Ắ' => 'A', // A with breve and acute
    'ắ' => 'a', // a with breve and acute
    'Ằ' => 'A', // A with breve and grave
    'ằ' => 'a', // a with breve and grave
    'Ẵ' => 'A', // A with breve and tilde
    'ẵ' => 'a', // a with breve and tilde
    'Ẳ' => 'A', // A with breve and hook above
    'ẳ' => 'a', // a with breve and hook above
    'A̧' => 'A', // A with cedilla
    'a̧' => 'a', // a with cedilla
    'Á̧' => 'A', // A with acute and cedilla
    'á̧' => 'a', // a with acute and cedilla
    'À̧' => 'A', // A with grave and cedilla
    'à̧' => 'a', // a with grave and cedilla
    'Â̧' => 'A', // A with circumflex and cedilla
    'â̧' => 'a', // a with circumflex and cedilla
    'Ǎ̧' => 'A', // A with caron and cedilla
    'ǎ̧' => 'a', // a with caron and cedilla
    'Â' => 'A', // A with circumflex
    'â' => 'a', // a with circumflex
    'Ấ' => 'A', // A with circumflex and acute
    'ấ' => 'a', // a with circumflex and acute
    'Ầ' => 'A', // A with circumflex and grave
    'ầ' => 'a', // a with circumflex and grave
    'Ẫ' => 'A', // A with circumflex and tilde
    'ẫ' => 'a', // a with circumflex and tilde
    'Ẩ' => 'A', // A with circumflex and hook above
    'ẩ' => 'a', // a with circumflex and hook above
    'A̭' => 'A', // A with circumflex below
    'a̭' => 'a', // a with circumflex below
    'Ǎ' => 'A', // A with caron
    'ǎ' => 'a', // a with caron
    'A̐' => 'A', // A with chandrabindu
    'a̐' => 'a', // a with chandrabindu
    'A̓' => 'A', // A with comma above
    'a̓' => 'a', // a with comma above
    'A̋' => 'A', // A with double acute
    'a̋' => 'a', // a with double acute
    'Å' => 'A', // A with ring above
    'å' => 'a', // a with ring above
    'Ǻ' => 'A', // A with ring above and acute
    'ǻ' => 'a', // a with ring above and acute
    'Å̂' => 'A', // A with ring above and circumflex
    'å̂' => 'a', // a with ring above and circumflex
    'Ä' => 'A', // A with diaeresis
    'ä' => 'a', // a with diaeresis
    'Ä́' => 'A', // A with diaeresis and acute
    'ä́' => 'a', // a with diaeresis and acute
    'Ä̀' => 'A', // A with diaeresis and grave
    'ä̀' => 'a', // a with diaeresis and grave
    'Ä̂' => 'A', // A with diaeresis and circumflex
    'ä̂' => 'a', // a with diaeresis and circumflex
    'Ä̌' => 'A', // A with diaeresis and caron
    'ä̌' => 'a', // a with diaeresis and caron
    'Ǟ' => 'A', // A with diaeresis and macron
    'ǟ' => 'a', // a with diaeresis and macron
    'Ã' => 'A', // A with tilde
    'ã' => 'a', // a with tilde
    'Ã́' => 'A', // A with tilde and acute
    'ã́' => 'a', // a with tilde and acute
    'Ã̀' => 'A', // A with tilde and grave
    'ã̀' => 'a', // a with tilde and grave
    'A̰' => 'A', // A with tilde below
    'a̰' => 'a', // a with tilde below
    'Ȧ' => 'A', // A with dot above
    'ȧ' => 'a', // a with dot above
    'Ȧ́' => 'A', // A with dot above and acute
    'ȧ́' => 'a', // a with dot above and acute
    'Ǡ' => 'A', // A with dot above and macron
    'ǡ' => 'a', // a with dot above and macron
    'Ą' => 'A', // A with ogonek
    'ą' => 'a', // a with ogonek
    'Ą́' => 'A', // A with acute and ogonek
    'ą́' => 'a', // a with acute and ogonek
    'Ą̀' => 'A', // A with grave and ogonek
    'ą̀' => 'a', // a with grave and ogonek
    'Ą̂' => 'A', // A with circumflex and ogonek
    'ą̂' => 'a', // a with circumflex and ogonek
    'Ą̌' => 'A', // A with acute and ogonek
    'ą̌' => 'a', // a with acute and ogonek
    'Ą̄' => 'A', // A with macron and ogonek
    'ą̄' => 'a', // a with macron and ogonek
    'Ą̄́' => 'A', // A with macron, acute and ogonek
    'ą̄́' => 'a', // a with macron, acute and ogonek
    'Ą̄̀' => 'A', // A with macron, grave and ogonek
    'ą̄̀' => 'a', // a with macron, grave and ogonek
    'Ą̄̂' => 'A', // A with macron, circumflex and ogonek
    'ą̄̂' => 'a', // a with macron, circumflex and ogonek
    'Ą̄̌' => 'A', // A with macron, caron and ogonek
    'ą̄̌' => 'a', // a with macron, caron and ogonek
    'Ā̊' => 'A', // A with macron and ring above
    'ā̊' => 'a', // a with macron and ring above
    'Ą̊' => 'A', // A with ring above and ogonek
    'ą̊' => 'a', // a with ring above and ogonek
    'Ą̃' => 'A', // A with tilde and ogonek
    'ą̃' => 'a', // a with tilde and ogonek
    'Ą̈' => 'A', // A with diaeresis and ogonek
    'ą̈' => 'a', // a with diaeresis and ogonek
    'Ą̈̀' => 'A', // A with diaeresis, grave and ogonek
    'ą̈̀' => 'a', // a with diaeresis, grave and ogonek
    'Ą̈̂' => 'A', // A with diaeresis, circumflex and ogonek
    'ą̈̂' => 'a', // a with diaeresis, circumflex and ogonek
    'Ą̈̌' => 'A', // A with diaeresis, caron and ogonek
    'ą̈̌' => 'a', // a with diaeresis, caron and ogonek
    'Ā' => 'A', // A with macron
    'ā' => 'a', // a with macron
    'Ā́' => 'A', // A with macron and acute
    'ā́' => 'a', // a with macron and acute
    'Ā̀' => 'A', // A with macron and grave
    'ā̀' => 'a', // a with macron and grave
    'Ā̂' => 'A', // A with macron and circumflex
    'ā̂' => 'a', // a with macron and circumflex
    'Ā̌' => 'A', // A with macron and caron
    'ā̌' => 'a', // a with macron and caron
    'Ā̆' => 'A', // A with macron and breve
    'ā̆' => 'a', // a with macron and breve
    'A̱' => 'A', // A with macron below
    'a̱' => 'a', // a with macron below
    'Á̱' => 'A', // A with macron below and acute
    'á̱' => 'a', // a with macron below and acute
    'À̱' => 'A', // A with macron below and grave
    'à̱' => 'a', // a with macron below and grave
    'Â̱' => 'A', // A with macron below and circumflex
    'â̱' => 'a', // a with macron below and circumflex
    'Ä̱' => 'A', // A with macron below and diaeresis
    'ä̱' => 'a', // a with macron below and diaeresis
    'Ā̱' => 'A', // A with macron below and macron
    'ā̱' => 'a', // a with macron below and macron
    'Å̱' => 'A', // A with macron below and ring above
    'å̱' => 'a', // a with macron below and ring above
    'Ả' => 'A', // A with hook above
    'ả' => 'a', // a with hook above
    'Ȁ' => 'A', // A with double grave
    'ȁ' => 'a', // a with double grave
    'Ȃ' => 'A', // A with inverted breve
    'ȃ' => 'a', // a with inverted breve
    'Ạ' => 'A', // A with dot below
    'ạ' => 'a', // a with dot below
    'Ạ́' => 'A', // A with acute and dot below
    'ạ́' => 'a', // a with acute and dot below
    'Ạ̀' => 'A', // A with grave and dot below
    'ạ̀' => 'a', // a with grave and dot below
    'Ặ' => 'A', // A with breve and dot below
    'ặ' => 'a', // a with breve and dot below
    'Ậ' => 'A', // A with circumflex and dot below
    'ậ' => 'a', // a with circumflex and dot below
    'Ạ̄' => 'A', // A with macron and dot below
    'ạ̄' => 'a', // a with macron and dot below
    'Ạ̈' => 'A', // A with diaeresis and dot below
    'ạ̈' => 'a', // a with diaeresis and dot below
    'Ạ̃' => 'A', // A with tilde and dot below
    'ạ̃' => 'a', // a with tilde and dot below
    'Ḁ' => 'A', // A with ring below
    'ḁ' => 'a', // a with ring below
    'A̍' => 'A', // A with vertical line
    'a̍' => 'a', // a with vertical line
    'B́' => 'B', // B with acute
    'b́' => 'b', // b with acute
    'B̓' => 'B', // B with comma above
    'b̓' => 'b', // b with comma above
    'Ḃ' => 'B', // B with dot above
    'ḃ' => 'b', // b with dot above
    'Ḅ' => 'B', // B with dot below
    'ḅ' => 'b', // b with dot below
    'Ḇ' => 'B', // B with line below
    'ḇ' => 'b', // b with line below
    'B̃' => 'B', // B with tilde
    'b̃' => 'b', // b with tilde
    'B̤' => 'B', // B with diaeresis below
    'b̤' => 'b', // b with diaeresis below
    'Ć' => 'C', // C with acute
    'ć' => 'c', // c with acute
    'C̀' => 'C', // C with grave
    'c̀' => 'c', // c with grave
    'Ĉ' => 'C', // C with circumflex
    'ĉ' => 'c', // c with circumflex
    'C̆' => 'C', // C with breve
    'c̆' => 'c', // c with breve
    'Č' => 'C', // C with caron
    'č' => 'c', // c with caron
    'Č̓' => 'C', // C with caron and comma above
    'č̓' => 'c', // c with caron and comma above
    'C̓' => 'C', // C with comma above
    'c̓' => 'c', // c with comma above
    'C̈' => 'C', // C with diaeresis
    'c̈' => 'c', // c with diaeresis
    'Ċ' => 'C', // C with dot above
    'ċ' => 'c', // c with dot above
    'C̣' => 'C', // C with dot below
    'c̣' => 'c', // c with dot below
    'Ç' => 'C', // C with cedilla
    'ç' => 'c', // c with cedilla
    'Ḉ' => 'C', // C with cedilla and acute
    'ḉ' => 'c', // c with cedilla and acute
    'Ç̆' => 'C', // C with cedilla and breve
    'ç̆' => 'c', // c with cedilla and breve
    'Ç̌' => 'C', // C with cedilla and caron
    'ç̌' => 'c', // c with cedilla and caron
    'Ç̇' => 'C', // C with cedilla and dot above
    'ç̇' => 'c', // c with cedilla and dot above
    'C̄' => 'C', // C with macron
    'c̄' => 'c', // c with macron
    'C̃' => 'C', // C with tilde
    'c̃' => 'c', // c with tilde
    'D́' => 'D', // D with acute
    'd́' => 'd', // d with acute
    'Ď' => 'D', // D with caron
    'ď' => 'd', // d with caron
    'Ḑ' => 'D', // D with cedilla
    'ḑ' => 'd', // d with cedilla
    'D̂' => 'D', // D with circumflex
    'd̂' => 'd', // d with circumflex
    'Ḓ' => 'D', // D with circumflex below
    'ḓ' => 'd', // d with circumflex below
    'D̓' => 'D', // D with comma above
    'd̓' => 'd', // d with comma above
    'D̦' => 'D', // D with comma below
    'd̦' => 'd', // d with comma below
    'Ḋ' => 'D', // D with dot above
    'ḋ' => 'd', // d with dot above
    'Ḍ' => 'D', // D with dot below
    'ḍ' => 'd', // d with dot below
    'Ḓ' => 'D', // D with circumflex below
    'ḓ' => 'd', // d with circumflex below
    'Ḏ' => 'D', // D with line below
    'ḏ' => 'd', // d with line below
    'D̤' => 'D', // D with diaeresis below
    'd̤' => 'd', // d with diaeresis below
    'Đ' => 'D', // D with stroke
    'đ' => 'd', // d with stroke
    'É' => 'E', // E with acute
    'é' => 'e', // e with acute
    'È' => 'E', // E with grave
    'è' => 'e', // e with grave
    'Ĕ' => 'E', // E with breve
    'ĕ' => 'e', // e with breve
    'Ě' => 'E', // E with caron
    'ě' => 'e', // e with caron
    'Ê' => 'E', // E with circumflex
    'ê' => 'e', // e with circumflex
    'Ế' => 'E', // E with circumflex and acute
    'ế' => 'e', // e with circumflex and acute
    'Ề' => 'E', // E with circumflex and grave
    'ề' => 'e', // e with circumflex and grave
    'Ễ' => 'E', // E with circumflex and tilde
    'ễ' => 'e', // e with circumflex and tilde
    'Ể' => 'E', // E with circumflex and hook above
    'ể' => 'e', // e with circumflex and hook above
    'Ë' => 'E', // E with diaeresis
    'ë' => 'e', // e with diaeresis
    'Ë́' => 'E', // E with diaeresis and acute
    'ë́' => 'e', // e with diaeresis and acute
    'Ë̀' => 'E', // E with diaeresis and grave
    'ë̀' => 'e', // e with diaeresis and grave
    'Ë̂' => 'E', // E with diaeresis and circumflex
    'ë̂' => 'e', // e with diaeresis and circumflex
    'Ë̌' => 'E', // E with diaeresis and caron
    'ë̌' => 'e', // e with diaeresis and caron
    'E̋' => 'E', // E with double acute
    'e̋' => 'e', // e with double acute
    'Ȅ' => 'E', // E with double grave
    'ȅ' => 'e', // e with double grave
    'Ẽ' => 'E', // E with tilde
    'ẽ' => 'e', // e with tilde
    'Ẽ́' => 'E', // E with tilde and acute
    'ẽ́' => 'e', // e with tilde and acute
    'Ẽ̀' => 'E', // E with tilde and grave
    'ẽ̀' => 'e', // e with tilde and grave
    'Ẽ̂' => 'E', // E with tilde and circumflex
    'ẽ̂' => 'e', // e with tilde and circumflex
    'Ẽ̌' => 'E', // E with tilde and caron
    'ẽ̌' => 'e', // e with tilde and caron
    'Ẽ̍' => 'E', // E with tilde and vertical line
    'ẽ̍' => 'e', // e with tilde and vertical line
    'Ė' => 'E', // E with dot above
    'ė' => 'e', // e with dot above
    'Ė́' => 'E', // E with dot above and acute
    'ė́' => 'e', // e with dot above and acute
    'Ė̃' => 'E', // E with dot and macron
    'ė̃' => 'e', // e with dot and macron
    'Ȩ' => 'E', // E with cedilla
    'ȩ' => 'e', // e with cedilla
    'Ȩ́' => 'E', // E with acute and cedilla
    'ȩ́' => 'e', // e with acute and cedilla
    'Ḝ' => 'E', // E with breve and cedilla
    'ḝ' => 'e', // e with breve and cedilla
    'Ȩ̀' => 'E', // E with grave and cedilla
    'ȩ̀' => 'e', // e with grave and cedilla
    'Ȩ̌' => 'E', // E with caron and cedilla
    'ȩ̌' => 'e', // e with caron and cedilla
    'Ȩ̂' => 'E', // E with circumflex and cedilla
    'ȩ̂' => 'e', // e with circumflex and cedilla
    'Ę' => 'E', // E with ogonek
    'ę' => 'e', // e with ogonek
    'Ę́' => 'E', // E with acute and ogonek
    'ę́' => 'e', // e with acute and ogonek
    'Ę̀' => 'E', // E with grave and ogonek
    'ę̀' => 'e', // e with grave and ogonek
    'Ę̂' => 'E', // E with circumflex and ogonek
    'ę̂' => 'e', // e with circumflex and ogonek
    'Ę̌' => 'E', // E with caron and ogonek
    'ę̌' => 'e', // e with caron and ogonek
    'Ę̄' => 'E', // E with macron and ogonek
    'ę̄' => 'e', // e with macron and ogonek
    'Ę̄́' => 'E', // E with macron, acute and ogonek
    'ę̄́' => 'e', // e with macron, acute and ogonek
    'Ę̄̀' => 'E', // E with macron, grave and ogonek
    'ę̄̀' => 'e', // e with macron, grave and ogonek
    'Ę̄̂' => 'E', // E with macron, circumflex and ogonek
    'ę̄̂' => 'e', // e with macron, circumflex and ogonek
    'Ę̄̌' => 'E', // E with macron, caron and ogonek
    'ę̄̌' => 'e', // e with macron, caron and ogonek
    'Ę̃' => 'E', // E with tilde and ogonek
    'ę̃' => 'e', // e with tilde and ogonek
    'Ę̈' => 'E', // E with diaeresis and ogonek
    'ę̈' => 'e', // e with diaeresis and ogonek
    'Ę̈̀' => 'E', // E with diaeresis, grave and ogonek
    'ę̈̀' => 'e', // e with diaeresis, grave and ogonek
    'Ę̈̂' => 'E', // E with diaeresis, circumflex and ogonek
    'ę̈̂' => 'e', // e with diaeresis, circumflex and ogonek
    'Ę̈̌' => 'E', // E with diaeresis, caron and ogonek
    'ę̈̌' => 'e', // e with diaeresis, caron and ogonek
    'Ę̇́' => 'E', // E with dot above, acute and ogonek
    'ę̇́' => 'e', // e with dot above, acute and ogonek
    'Ę̋' => 'E', // E with double acute and ogonek
    'ę̋' => 'e', // e with double acute and ogonek
    'Ę̇' => 'E', // E with dot above and ogonek
    'ę̇' => 'e', // e with dot above and ogonek
    'Ę̣' => 'E', // E with ogonek and dot below
    'ę̣' => 'e', // e with ogonek and dot below
    'Ē' => 'E', // E with macron
    'ē' => 'e', // e with macron
    'Ḗ' => 'E', // E with macron and acute
    'ḗ' => 'e', // e with macron and acute
    'Ē̆' => 'E', // E with macron and breve
    'ē̆' => 'e', // e with macron and breve
    'Ḕ' => 'E', // E with macron and grave
    'ḕ' => 'e', // e with macron and grave
    'Ē̂' => 'E', // E with macron and circumflex
    'ē̂' => 'e', // e with macron and circumflex
    'Ē̌' => 'E', // E with macron and caron
    'ē̌' => 'e', // e with macron and caron
    'Ẻ' => 'E', // E with hook above
    'ẻ' => 'e', // e with hook above
    'Ȅ' => 'E', // E with double grave
    'ȅ' => 'e', // e with double grave
    'Ȇ' => 'E', // E with inverted breve
    'ȇ' => 'e', // e with inverted breve
    'E̍' => 'E', // E with vertical line
    'e̍' => 'e', // e with vertical line
    'Ȩ' => 'E', // E with cedilla
    'ȩ' => 'e', // e with cedilla
    'Ḝ' => 'E', // E with breve and cedilla
    'ḝ' => 'e', // e with breve and cedilla
    'Ẹ' => 'E', // E with dot below
    'ẹ' => 'e', // e with dot below
    'Ệ' => 'E', // E with circumflex and dot below
    'ệ' => 'e', // e with circumflex and dot below
    'Ẹ́' => 'E', // E with acute and dot below
    'ẹ́' => 'e', // e with acute and dot below
    'Ẹ̀' => 'E', // E with grave and dot below
    'ẹ̀' => 'e', // e with grave and dot below
    'Ẹ̄' => 'E', // E with macron and dot below
    'ẹ̄' => 'e', // e with macron and dot below
    'Ḙ' => 'E', // E with circumflex below
    'ḙ' => 'e', // e with circumflex below
    'E̱' => 'E', // E with macron below
    'e̱' => 'e', // e with macron below
    'É̱' => 'E', // E with acute and macron below
    'é̱' => 'e', // e with acute and macron below
    'È̱' => 'E', // E with grave and macron below
    'è̱' => 'e', // e with grave and macron below
    'Ê̱' => 'E', // E with circumflex and macron below
    'ê̱' => 'e', // e with circumflex and macron below
    'Ē̱' => 'E', // E with macron and macron below
    'ē̱' => 'e', // e with macron and macron below
    'Ë̱' => 'E', // E with diaeresis and macron below
    'ë̱' => 'e', // e with diaeresis and macron below
    'Ḛ' => 'E', // E with tilde below
    'ḛ' => 'e', // e with tilde below
    'E̊' => 'E', // E with ring
    'e̊' => 'e', // e with ring
    'F́' => 'F', // F with acute
    'f́' => 'f', // f with acute
    'F̀' => 'F', // F with grave
    'f̀' => 'f', // f with grave
    'Ḟ' => 'F', // F with dot above
    'ḟ' => 'f', // f with dot above
    'F̄' => 'F', // F with macron
    'f̄' => 'f', // f with macron
    'F̧' => 'F', // F with cedilla
    'f̧' => 'f', // f with cedilla
    'F̣' => 'F', // F with dot below
    'f̣' => 'f', // f with dot below
    'Ǵ' => 'G', // G with acute
    'ǵ' => 'g', // g with acute
    'G̀' => 'G', // G with grave
    'g̀' => 'g', // g with grave
    'Ğ' => 'G', // G with breve
    'ğ' => 'g', // g with breve
    'Ĝ' => 'G', // G with circumflex
    'ĝ' => 'g', // g with circumflex
    'Ǧ' => 'G', // G with caron
    'ǧ' => 'g', // g with caron
    'Ġ' => 'G', // G with dot above
    'ġ' => 'g', // g with dot above
    'G̣' => 'G', // G with dot below
    'g̣' => 'g', // g with dot below
    'Ģ' => 'G', // G with cedilla
    'ģ' => 'g', // g with cedilla
    'Ḡ' => 'G', // G with macron
    'ḡ' => 'g', // g with macron
    'G̈' => 'G', // G with diaeresis
    'g̈' => 'g', // g with diaeresis
    'G̤' => 'G', // G with diaeresis below
    'g̤' => 'g', // g with diaeresis below
    'G̃' => 'G', // G with tilde
    'g̃' => 'g', // g with tilde
    'Ǥ' => 'G', // G with stroke
    'ǥ' => 'g', // g with stroke
    'H́' => 'H', // H with acute
    'h́' => 'h', // h with acute
    'Ĥ' => 'H', // H with circumflex
    'ĥ' => 'h', // h with circumflex
    'Ȟ' => 'H', // H with caron
    'ȟ' => 'h', // h with caron
    'Ḧ' => 'H', // H with diaeresis
    'ḧ' => 'h', // h with diaeresis
    'H̤' => 'H', // H with diaeresis below
    'h̤' => 'h', // h with diaeresis below
    'H̄' => 'H', // H with macron
    'h̄' => 'h', // h with macron
    'Ḣ' => 'H', // H with dot above
    'ḣ' => 'h', // h with dot above
    'H̐' => 'H', // H with chandrabindu
    'h̐' => 'h', // h with chandrabindu
    'H̓' => 'H', // H with comma above
    'h̓' => 'h', // h with comma above
    'Ḣ' => 'H', // H with dot above
    'ḣ' => 'h', // h with dot above
    'Ḩ' => 'H', // H with cedilla
    'ḩ' => 'h', // h with cedilla
    'Ḥ' => 'H', // H with dot below
    'ḥ' => 'h', // h with dot below
    'Ḫ' => 'H', // H with breve below
    'ḫ' => 'h', // h with breve below
    'H̱' => 'H', // H with line below
    'ẖ' => 'h', // h with line below
    'Ħ' => 'H', // H with stroke
    'ħ' => 'h', // h with stroke
    'Í' => 'I', // I with acute
    'í' => 'i', // i with acute
    'Ì' => 'I', // I with grave
    'ì' => 'i', // i with grave
    'Ĭ' => 'I', // I with breve
    'ĭ' => 'i', // i with breve
    'Î' => 'I', // I with circumflex
    'î' => 'i', // i with circumflex
    'Î́' => 'I', // I with circumflex and acute
    'î́' => 'i', // i with circumflex and acute
    'Ǐ' => 'I', // I with caron
    'ǐ' => 'i', // i with caron
    'Ï' => 'I', // I with diaeresis
    'ï' => 'i', // i with diaeresis
    'Ḯ' => 'I', // I with diaeresis and acute
    'ḯ' => 'i', // i with diaeresis and acute
    'Ĩ' => 'I', // I with tilde
    'ĩ' => 'i', // i with tilde
    'Ĩ́' => 'I', // I with tilde and acute
    'ĩ́' => 'i', // i with tilde and acute
    'Ĩ̀' => 'I', // I with tilde and grave
    'ĩ̀' => 'i', // i with tilde and grave
    'Ĩ̂' => 'I', // I with tilde and circumflex
    'ĩ̂' => 'i', // i with tilde and circumflex
    'Ĩ̌' => 'I', // I with tilde and caron
    'ĩ̌' => 'i', // i with tilde and caron
    'Ĩ̍' => 'I', // I with tilde and vertical line
    'ĩ̍' => 'i', // i with tilde and vertical line
    'İ' => 'I', // I (uppercase) with dot above
    'i' => 'i', // i (uppercase) with dot above
    'I' => 'I', // I (lowercase, i.e. ı) without dot above
    'Į' => 'I', // I with ogonek
    'į' => 'i', // i with ogonek
    'Į́' => 'I', // I with ogonek and acute
    'į́' => 'i', // i with ogonek and acute
    'Į̀' => 'I', // I with ogonek and grave
    'į̀' => 'i', // i with ogonek and grave
    'Į̂' => 'I', // I with ogonek and circumflex
    'į̂' => 'i', // i with ogonek and circumflex
    'Į̌' => 'I', // I with ogonek and caron
    'į̌' => 'i', // i with ogonek and caron
    'Į̃' => 'I', // I with ogonek and tilde
    'į̃' => 'i', // i with ogonek and tilde
    'Ī' => 'I', // I with macron
    'ī' => 'i', // i with macron
    'Ī́' => 'I', // I with macron and acute
    'ī́' => 'i', // i with macron and acute
    'Ī̀' => 'I', // I with macron and grave
    'ī̀' => 'i', // i with macron and grave
    'Ī̂' => 'I', // I with macron and circumflex
    'ī̂' => 'i', // i with macron and circumflex
    'Ī̌' => 'I', // I with macron and caron
    'ī̌' => 'i', // i with macron and caron
    'Ỉ' => 'I', // I with hook above
    'ỉ' => 'i', // i with hook above
    'Ȉ' => 'I', // I with double grave
    'ȉ' => 'i', // i with double grave
    'Ȋ' => 'I', // I with inverted breve
    'ȋ' => 'i', // i with inverted breve
    'I̋' => 'I', // I with double acute
    'i̋' => 'i', // i with double acute
    'Ȉ' => 'I', // I with double grave
    'ȉ' => 'i', // i with double grave
    'I̍' => 'I', // I with vertical line
    'i̍' => 'i', // i with vertical line
    'I̐' => 'I', // I with chandrabindu
    'i̐' => 'i', // i with chandrabindu
    'I̓' => 'I', // I with comma above
    'i̓' => 'i', // i with comma above
    'I̧' => 'I', // I with cedilla
    'i̧' => 'i', // i with cedilla
    'Í̧' => 'I', // I with cedilla and acute
    'í̧' => 'i', // i with cedilla and acute
    'Ì̧' => 'I', // I with cedilla and grave
    'ì̧' => 'i', // i with cedilla and grave
    'Î̧' => 'I', // I with cedilla and circumflex
    'î̧' => 'i', // i with cedilla and circumflex
    'I̱' => 'I', // I with line below
    'i̱' => 'i', // i with line below
    'Í̱' => 'I', // I with line below and acute
    'í̱' => 'i', // i with line below and acute
    'Ì̱' => 'I', // I with line below and grave
    'ì̱' => 'i', // i with line below and grave
    'Î̱' => 'I', // I with line below and circumflex
    'î̱' => 'i', // i with line below and circumflex
    'Ī̱' => 'I', // I with line below and macron
    'ī̱' => 'i', // i with line below and macron
    'Ị' => 'I', // I with dot below
    'ị' => 'i', // i with dot below
    'Ị́' => 'I', // I with dot below and acute
    'ị́' => 'i', // i with dot below and acute
    'Ị̂' => 'I', // I with dot below and circumflex
    'ị̂' => 'i', // i with dot below and circumflex
    'Ị̃' => 'I', // I with dot below and tilde
    'ị̃' => 'i', // i with dot below and tilde
    'Ḭ' => 'I', // I with tilde below
    'ḭ' => 'i', // i with tilde below
    'J́' => 'J', // J with acute
    'j́' => 'j', // j with acute
    'Ĵ' => 'J', // J with circumflex
    'ĵ' => 'j', // j with circumflex
    'J̌' => 'J', // J with caron
    'ǰ' => 'j', // j with caron
    'J̄' => 'J', // J with macron
    'j̄' => 'j', // j with macron
    'J̃' => 'J', // J with tilde
    'j̃' => 'j', // j with tilde
    'J̣' => 'J', // J with dot below
    'j̣' => 'j', // j with dot below
    'Ḱ' => 'K', // K with acute
    'ḱ' => 'k', // k with acute
    'K̀' => 'K', // K with grave
    'k̀' => 'k', // k with grave
    'Ǩ' => 'K', // K with caron
    'ǩ' => 'k', // k with caron
    'K̄' => 'K', // K with macron
    'k̄' => 'k', // k with macron
    'K̇' => 'K', // K with dot above
    'k̇' => 'k', // k with dot above
    'Ķ' => 'K', // K with cedilla
    'ķ' => 'k', // k with cedilla
    'Ḳ' => 'K', // K with dot below
    'ḳ' => 'k', // k with dot below
    'Ḵ' => 'K', // K with line below
    'ḵ' => 'k', // k with line below
    'Ĺ' => 'L', // L with acute
    'ĺ' => 'l', // l with acute
    'L̂' => 'L', // L with circumflex
    'l̂' => 'l', // l with circumflex
    'L̐' => 'L', // L with chandrabindu
    'l̐' => 'l', // l with chandrabindu
    'L̃' => 'L', // L with tilde
    'l̃' => 'l', // l with tilde
    'L̓' => 'L', // L with comma above
    'l̓' => 'l', // l with comma above
    'Ľ' => 'L', // L with caron
    'ľ' => 'l', // l with caron
    'Ļ' => 'L', // L with cedilla
    'ļ' => 'l', // l with cedilla
    'L̦' => 'L', // L with comma below
    'l̦' => 'l', // l with comma below
    'Ḷ' => 'L', // L with dot below
    'ḷ' => 'l', // l with dot below
    'Ḹ' => 'L', // L with dot below and macron
    'ḹ' => 'l', // l with dot below and macron
    'Ḷ́' => 'L', // L with acute and dot below
    'ḷ́' => 'l', // l with acute and dot below
    'Ḷ̓' => 'L', // L with comma above and dot below
    'ḷ̓' => 'l', // l with comma above and dot below
    'Ḽ' => 'L', // L with circumflex below
    'ḽ' => 'l', // l with circumflex below
    'Ḻ' => 'L', // L with line below
    'ḻ' => 'l', // l with line below
    'Ł' => 'L', // L with stroke
    'ł' => 'l', // l with stroke
    'Ḿ' => 'M', // M with acute
    'ḿ' => 'm', // m with acute
    'M̀' => 'M', // M with grave
    'm̀' => 'm', // m with grave
    'Ṁ' => 'M', // M with dot above
    'ṁ' => 'm', // m with dot above
    'Ṃ' => 'M', // M with dot below
    'ṃ' => 'm', // m with dot below
    'M̍' => 'M', // M with vertical line
    'm̍' => 'm', // m with vertical line
    'M̄' => 'M', // M with macron
    'm̄' => 'm', // m with macron
    'M̐' => 'M', // M with chandrabindu
    'm̐' => 'm', // m with chandrabindu
    'M̃' => 'M', // M with tilde
    'm̃' => 'm', // m with tilde
    'M̈' => 'M', // M with diaeresis
    'm̈' => 'm', // m with diaeresis
    'M̓' => 'M', // M with comma above
    'm̓' => 'm', // m with comma above
    'M̧' => 'M', // M with cedilla
    'm̧' => 'm', // m with cedilla
    'M̨' => 'M', // M with ogonek
    'm̨' => 'm', // m with ogonek
    'Ṃ' => 'M', // M with dot below
    'ṃ' => 'm', // m with dot below
    'Ṃ́' => 'M', // M with acute and dot below
    'ṃ́' => 'm', // m with acute and dot below
    'Ṃ̓' => 'M', // M with comma above and dot below
    'ṃ̓' => 'm', // m with comma above and dot below
    'M̦' => 'M', // M with comma below
    'm̦' => 'm', // m with comma below
    'Ń' => 'N', // N with acute
    'ń' => 'n', // n with acute
    'Ǹ' => 'N', // N with grave
    'ǹ' => 'n', // n with grave
    'N̂' => 'N', // N with circumflex
    'n̂' => 'n', // n with circumflex
    'Ň' => 'N', // N with caron
    'ň' => 'n', // n with caron
    'Ñ' => 'N', // N with tilde
    'ñ' => 'n', // n with tilde
    'Ñ̈' => 'N', // N with tidle and diaeresis
    'ñ̈' => 'n', // n with tidle and diaeresis
    'Ṅ' => 'N', // N with dot above
    'ṅ' => 'n', // n with dot above
    'N̍' => 'N', // N with vertical line
    'n̍' => 'n', // n with vertical line
    'N̄' => 'N', // N with macron
    'n̄' => 'n', // n with macron
    'N̐' => 'N', // N with chandrabindu
    'n̐' => 'n', // n with chandrabindu
    'N̈' => 'N', // N with diaresis
    'n̈' => 'n', // n with diaresis
    'Ņ' => 'N', // N with cedilla
    'ņ' => 'n', // n with cedilla
    'Ṋ' => 'N', // N with circumflex below
    'ṋ' => 'n', // n with circumflex below
    'N̦' => 'N', // N with comma below
    'n̦' => 'n', // n with comma below
    'Ṇ' => 'N', // N with dot below
    'ṇ' => 'n', // n with dot below
    'Ṇ́' => 'N', // N with acute and dot below
    'ṇ́' => 'n', // n with acute and dot below
    'Ṇ̓' => 'N', // N with comma above and dot below
    'ṇ̓' => 'n', // n with comma above and dot below
    'Ṉ' => 'N', // N with line below
    'ṉ' => 'n', // n with line below
    'N̰' => 'N', // N with tilde below
    'n̰' => 'n', // n with tilde below
    'N̲' => 'N', // N with underline
    'n̲' => 'n', // n with underline
    'Ó' => 'O', // O with acute
    'ó' => 'o', // o with acute
    'Ò' => 'O', // O with grave
    'ò' => 'o', // o with grave
    'Ŏ' => 'O', // O with breve
    'ŏ' => 'o', // o with breve
    'Ô' => 'O', // O with circumflex
    'ô' => 'o', // o with circumflex
    'Ố' => 'O', // O with circumflex and acute
    'ố' => 'o', // o with circumflex and acute
    'Ồ' => 'O', // O with circumflex and grave
    'ồ' => 'o', // o with circumflex and grave
    'Ỗ' => 'O', // O with circumflex and tilde
    'ỗ' => 'o', // o with circumflex and tilde
    'Ổ' => 'O', // O with circumflex and hook above
    'ổ' => 'o', // o with circumflex and hook above
    'Ǒ' => 'O', // O with caron
    'ǒ' => 'o', // o with caron
    'O̐' => 'O', // O with chandrabindu
    'o̐' => 'o', // o with chandrabindu
    'Ö' => 'O', // O with diaeresis
    'ö' => 'o', // o with diaeresis
    'Ö́' => 'O', // O with diaeresis and acute
    'ö́' => 'o', // o with diaeresis and acute
    'Ö̀' => 'O', // O with diaeresis and grave
    'ö̀' => 'o', // o with diaeresis and grave
    'Ȫ' => 'O', // O with diaeresis and macron
    'ȫ' => 'o', // o with diaeresis and macron
    'Ő' => 'O', // O with double acute
    'ő' => 'o', // o with double acute
    'Õ' => 'O', // O with tilde
    'õ' => 'o', // o with tilde
    'Ṍ' => 'O', // O with tilde and acute
    'ṍ' => 'o', // o with tilde and acute
    'Ṏ' => 'O', // O with tilde and diaeresis
    'ṏ' => 'o', // o with tilde and diaeresis
    'Ȭ' => 'O', // O with tilde and macron
    'ȭ' => 'o', // o with tilde and macron
    'Ȯ' => 'O', // O with dot above
    'ȯ' => 'o', // o with dot above
    'Ȱ' => 'O', // O with dot above and macron
    'ȱ' => 'o', // o with dot above and macron
    'Ø' => 'O', // O with stroke
    'ø' => 'o', // o with stroke
    'Ǿ' => 'O', // O with stroke and acute
    'ǿ' => 'o', // o with stroke and acute
    'Ø̀' => 'O', // O with stroke and grave
    'ø̀' => 'o', // o with stroke and grave
    'Ø̂' => 'O', // O with stroke and circumflex
    'ø̂' => 'o', // o with stroke and circumflex
    'Ø̌' => 'O', // O with stroke and caron
    'ø̌' => 'o', // o with stroke and caron
    'Ø̄' => 'O', // O with stroken and macron
    'ø̄' => 'o', // o with stroken and macron
    'Ǫ' => 'O', // O with ogonek
    'ǫ' => 'o', // o with ogonek
    'Ǭ' => 'O', // O with macron and ogonek
    'ǭ' => 'o', // o with macron and ogonek
    'Ǭ̀' => 'O', // O with macron, grave and ogonek
    'ǭ̀' => 'o', // o with macron, grave and ogonek
    'Ǫ́' => 'O', // O with acute and ogonek
    'ǫ́' => 'o', // o with acute and ogonek
    'Ǫ̀' => 'O', // O with grave and ogonek
    'ǫ̀' => 'o', // o with grave and ogonek
    'Ǫ̂' => 'O', // O with circumflex and ogonek
    'ǫ̂' => 'o', // o with circumflex and ogonek
    'Ǫ̌' => 'O', // O with caron and ogonek
    'ǫ̌' => 'o', // o with caron and ogonek
    'Ō' => 'O', // O with macron
    'ō' => 'o', // o with macron
    'Ṓ' => 'O', // O with macron and acute
    'ṓ' => 'o', // o with macron and acute
    'Ṑ' => 'O', // O with macron and grave
    'ṑ' => 'o', // o with macron and grave
    'Ō̂' => 'O', // O with macron and circumflex
    'ō̂' => 'o', // o with macron and circumflex
    'Ō̌' => 'O', // O with macron and caron
    'ō̌' => 'o', // o with macron and caron
    'Ỏ' => 'O', // O with hook above
    'ỏ' => 'o', // o with hook above
    'Ő' => 'O', // O with double acute
    'ő' => 'o', // o with double acute
    'Ȍ' => 'O', // O with double grave
    'ȍ' => 'o', // o with double grave
    'Ȏ' => 'O', // O with inverted breve
    'ȏ' => 'o', // o with inverted breve
    'Ơ' => 'O', // O with horn
    'ơ' => 'o', // o with horn
    'Ớ' => 'O', // O with horn and acute
    'ớ' => 'o', // o with horn and acute
    'Ờ' => 'O', // O with horn and grave
    'ờ' => 'o', // o with horn and grave
    'Ỡ' => 'O', // O with horn and tilde
    'ỡ' => 'o', // o with horn and tilde
    'Ở' => 'O', // O with horn and hook above
    'ở' => 'o', // o with horn and hook above
    'O̍' => 'O', // O with vertical line
    'o̍' => 'o', // o with vertical line
    'Ọ' => 'O', // O with dot below
    'ọ' => 'o', // o with dot below
    'Ọ́' => 'O', // O with acute and dot below
    'ọ́' => 'o', // o with acute and dot below
    'Ọ̀' => 'O', // O with grave and dot below
    'ọ̀' => 'o', // o with grave and dot below
    'Ộ' => 'O', // O with circumflex and dot below
    'ộ' => 'o', // o with circumflex and dot below
    'Ọ̄' => 'O', // O with macron and dot below
    'ọ̄' => 'o', // o with macron and dot below
    'Ợ' => 'O', // O with horn and dot below
    'ợ' => 'o', // o with horn and dot below
    'Ộ' => 'O', // O with circumflex and dot below
    'ộ' => 'o', // o with circumflex and dot below
    'O̭' => 'O', // O with circumflex below
    'o̭' => 'o', // o with circumflex below
    'O̧' => 'O', // O with cedilla
    'o̧' => 'o', // o with cedilla
    'Ó̧' => 'O', // O with acute and cedilla
    'ó̧' => 'o', // o with acute and cedilla
    'Ò̧' => 'O', // O with grave and cedilla
    'ò̧' => 'o', // o with grave and cedilla
    'Ô̧' => 'O', // O with circumflex and cedilla
    'ô̧' => 'o', // o with circumflex and cedilla
    'Ǒ̧' => 'O', // O with caron and cedilla
    'ǒ̧' => 'o', // o with caron and cedilla
    'O̱' => 'O', // O with line below
    'o̱' => 'o', // o with line below
    'Ó̱' => 'O', // O with acute and line below
    'ó̱' => 'o', // o with acute and line below
    'Ò̱' => 'O', // O with grave and line below
    'ò̱' => 'o', // o with grave and line below
    'Ô̱' => 'O', // O with circumflex and line below
    'ô̱' => 'o', // o with circumflex and line below
    'Ō̱' => 'O', // O with macron and line below
    'ō̱' => 'o', // o with macron and line below
    'Ö̱' => 'O', // O with diaeresis and line below
    'ö̱' => 'o', // o with diaeresis and line below
    'O̲' => 'O', // O with underline
    'o̲' => 'o', // o with underline
    'Ṕ' => 'P', // P with acute
    'ṕ' => 'p', // p with acute
    'P̀' => 'P', // P with grave
    'p̀' => 'p', // p with grave
    'Ṗ' => 'P', // P with dot above
    'ṗ' => 'p', // p with dot above
    'P̣' => 'P', // P with dot above below
    'p̣' => 'p', // p with dot above below
    'P̄' => 'P', // P with macron
    'p̄' => 'p', // p with macron
    'P̓' => 'P', // P with comma above
    'p̓' => 'p', // p with comma above
    'P̈' => 'P', // P with diaeresis
    'p̈' => 'p', // p with diaeresis
    'P̤' => 'P', // P with diaeresis below
    'p̤' => 'p', // p with diaeresis below
    'P̄' => 'P', // P with tilde
    'p̄' => 'p', // p with tilde
    'Q̓' => 'Q', // Q with comma above
    'q̓' => 'q', // q with comma above
    'Q̇' => 'Q', // Q with dot above
    'q̇' => 'q', // q with dot above
    'Ŕ' => 'R', // R with acute
    'ŕ' => 'r', // r with acute
    'Ř' => 'R', // R with caron
    'ř' => 'r', // r with caron
    'R̂' => 'R', // R with circumflex
    'r̂' => 'r', // r with circumflex
    'R̓' => 'R', // R with comma above
    'r̓' => 'r', // r with comma above
    'R̦' => 'R', // R with comma below
    'r̦' => 'r', // r with comma below
    'Ṙ' => 'R', // R with dot above
    'ṙ' => 'r', // r with dot above
    'Ŗ' => 'R', // R with cedilla
    'ŗ' => 'r', // r with cedilla
    'R̄' => 'R', // R with macron
    'r̄' => 'r', // r with macron
    'Ȑ' => 'R', // R with double grave
    'ȑ' => 'r', // r with double grave
    'Ȓ' => 'R', // R with inverted breve
    'ȓ' => 'r', // r with inverted breve
    'Ṛ' => 'R', // R with dot below
    'ṛ' => 'r', // r with dot below
    'Ṝ' => 'R', // R with dot below and macron
    'ṝ' => 'r', // r with dot below and macron
    'R̰' => 'R', // R with diaeresis below
    'r̰' => 'r', // r with diaeresis below
    'Ṟ' => 'R', // R with line below
    'ṟ' => 'r', // r with line below
    'R̥' => 'R', // R with ring below
    'r̥' => 'r', // r with ring below
    'R̥̄' => 'R', // R with ring below and macron
    'r̥̄' => 'r', // r with ring below and macron
    'R̃' => 'R', // R with tilde
    'r̃' => 'r', // r with tilde
    'Ś' => 'S', // S with acute
    'ś' => 's', // s with acute
    'Ṥ' => 'S', // S with acute and dot above
    'ṥ' => 's', // s with acute and dot above
    'Ŝ' => 'S', // S with circumflex
    'ŝ' => 's', // s with circumflex
    'Š' => 'S', // S with caron
    'š' => 's', // s with caron
    'Ṧ' => 'S', // S with caron and dot above
    'ṧ' => 's', // s with caron and dot above
    'Ṡ' => 'S', // S with dot above
    'ṡ' => 's', // s with dot above
    'Ş' => 'S', // S with cedilla
    'ş' => 's', // s with cedilla
    'Ṣ' => 'S', // S with dot below
    'ṣ' => 's', // s with dot below
    'Ṩ' => 'S', // S with dot below and dot above
    'ṩ' => 's', // s with dot below and dot above
    'Ș' => 'S', // S with comma below
    'ș' => 's', // s with comma below
    'Ť' => 'T', // T with caron
    'ť' => 't', // t with caron
    'T̈' => 'T', // T with diaeresis
    'ẗ' => 't', // t with diaeresis
    'Ṫ' => 'T', // T with dot above
    'ṫ' => 't', // t with dot above
    'Ţ' => 'T', // T with cedilla
    'ţ' => 't', // t with cedilla
    'Ṭ' => 'T', // T with dot below
    'ṭ' => 't', // t with dot below
    'Ț' => 'T', // T with comma below
    'ț' => 't', // t with comma below
    'Ṱ' => 'T', // T with circumflex below
    'ṱ' => 't', // t with circumflex below
    'Ṯ' => 'T', // T with line below
    'ṯ' => 't', // t with line below
    'Ŧ' => 'T', // T with stroke
    'ŧ' => 't', // t with stroke
    'Ú' => 'U', // U with acute
    'ú' => 'u', // u with acute
    'Ù' => 'U', // U with grave
    'ù' => 'u', // u with grave
    'Ŭ' => 'U', // U with breve
    'ŭ' => 'u', // u with breve
    'Û' => 'U', // U with circumflex
    'û' => 'u', // u with circumflex
    'Ǔ' => 'U', // U with caron
    'ǔ' => 'u', // u with caron
    'Ů' => 'U', // U with ring above
    'ů' => 'u', // u with ring above
    'Ü' => 'U', // U with diaeresis
    'ü' => 'u', // u with diaeresis
    'Ǘ' => 'U', // U with diaeresis and acute
    'ǘ' => 'u', // u with diaeresis and acute
    'Ǜ' => 'U', // U with diaeresis and grave
    'ǜ' => 'u', // u with diaeresis and grave
    'Ǚ' => 'U', // U with diaeresis and caron
    'ǚ' => 'u', // u with diaeresis and caron
    'Ǖ' => 'U', // U with diaeresis and macron
    'ǖ' => 'u', // u with diaeresis and macron
    'Ű' => 'U', // U with double acute
    'ű' => 'u', // u with double acute
    'Ũ' => 'U', // U with tilde
    'ũ' => 'u', // u with tilde
    'Ṹ' => 'U', // U with tilde and acute
    'ṹ' => 'u', // u with tilde and acute
    'Ų' => 'U', // U with ogonek
    'ų' => 'u', // u with ogonek
    'Ū' => 'U', // U with macron
    'ū' => 'u', // u with macron
    'Ṻ' => 'U', // U with macron and diaeresis
    'ṻ' => 'u', // u with macron and diaeresis
    'Ủ' => 'U', // U with hook above
    'ủ' => 'u', // u with hook above
    'Ȕ' => 'U', // U with double grave
    'ȕ' => 'u', // u with double grave
    'Ȗ' => 'U', // U with inverted breve
    'ȗ' => 'u', // u with inverted breve
    'Ư' => 'U', // U with horn
    'ư' => 'u', // u with horn
    'Ứ' => 'U', // U with horn and acute
    'ứ' => 'u', // u with horn and acute
    'Ừ' => 'U', // U with horn and grave
    'ừ' => 'u', // u with horn and grave
    'Ữ' => 'U', // U with horn and tilde
    'ữ' => 'u', // u with horn and tilde
    'Ử' => 'U', // U with horn and hook above
    'ử' => 'u', // u with horn and hook above
    'Ự' => 'U', // U with horn and dot below
    'ự' => 'u', // u with horn and dot below
    'Ụ' => 'U', // U with dot below
    'ụ' => 'u', // u with dot below
    'Ṳ' => 'U', // U with diaeresis below
    'ṳ' => 'u', // u with diaeresis below
    'Ṷ' => 'U', // U with circumflex below
    'ṷ' => 'u', // u with circumflex below
    'Ṵ' => 'U', // U with tilde below
    'ṵ' => 'u', // u with tilde below
    'Ṽ' => 'V', // V with tilde
    'ṽ' => 'v', // v with tilde
    'Ṿ' => 'V', // V with dot below
    'ṿ' => 'v', // v with dot below
    'Ẃ' => 'W', // W with acute
    'ẃ' => 'w', // w with acute
    'Ẁ' => 'W', // W with grave
    'ẁ' => 'w', // w with grave
    'Ŵ' => 'W', // W with circumflex
    'ŵ' => 'w', // w with circumflex
    'W̊' => 'W', // W with ring above
    'ẘ' => 'w', // w with ring above
    'Ẅ' => 'W', // W with diaeresis
    'ẅ' => 'w', // w with diaeresis
    'Ẇ' => 'W', // W with dot above
    'ẇ' => 'w', // w with dot above
    'Ẉ' => 'W', // W with dot below
    'ẉ' => 'w', // w with dot below
    'Ẍ' => 'X', // X with diaeresis
    'ẍ' => 'x', // x with diaeresis
    'Ẋ' => 'X', // X with dot above
    'ẋ' => 'x', // x with dot above
    'Ý' => 'Y', // Y with acute
    'ý' => 'y', // y with acute
    'Ỳ' => 'Y', // Y with grave
    'ỳ' => 'y', // y with grave
    'Ŷ' => 'Y', // Y with circumflex
    'ŷ' => 'y', // y with circumflex
    'Y̊' => 'Y', // Y with ring above
    'ẙ' => 'y', // y with ring above
    'Ÿ' => 'Y', // Y with diaeresis
    'ÿ' => 'y', // y with diaeresis
    'Ỹ' => 'Y', // Y with tilde
    'ỹ' => 'y', // y with tilde
    'Ẏ' => 'Y', // Y with dot above
    'ẏ' => 'y', // y with dot above
    'Ȳ' => 'Y', // Y with macron
    'ȳ' => 'y', // y with macron
    'Ỷ' => 'Y', // Y with hook above
    'ỷ' => 'y', // y with hook above
    'Ỵ' => 'Y', // Y with dot below
    'ỵ' => 'y', // y with dot below
    'Ź' => 'Z', // Z with acute
    'ź' => 'z', // z with acute
    'Ẑ' => 'Z', // Z with circumflex
    'ẑ' => 'z', // z with circumflex
    'Ž' => 'Z', // Z with caron
    'ž' => 'z', // z with caron
    'Ż' => 'Z', // Z with dot above
    'ż' => 'z', // z with dot above
    'Ẓ' => 'Z', // Z with dot below
    'ẓ' => 'z', // z with dot below
    'Ẕ' => 'Z', // Z with line below
    'ẕ' => 'z', // z with line below
);
